default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: dig_dns_app_dev

test:
  <<: *default
  database: dig_dns_app_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

cable:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
